### ISSUE TITLE
Missing clinicalTrial and validityPeriod extensions

### ISSUE THREAD

**Issue by c-schuler** [HL7/fhir-qi-core#38]
FHIR STU3 had extensions for [Patient.clinicalTrial](http://hl7.org/fhir/STU3/extension-patient-clinicaltrial.html) and [MedicationDispense.validityPeriod](http://hl7.org/fhir/STU3/extension-medicationdispense-validityperiod.html), but it appears as though they were removed in FHIR R4.

Need to include these extensions in the IG as the QDM to QiCore mappings expect and reference them.

**Comment by brynrhodes** [comment]
This needs to be submitted as a JIRA tracker, since it concerns balloted content.
