### ISSUE TITLE
Missing links to negation examples FHIR-24045

### ISSUE THREAD

**Issue by p9g** [HL7/fhir-qi-core#71]
The following pages are listed in ig.json but are not linked from https://github.com/HL7/fhir-qi-core/blob/master/pages/examples.md 

- "Communication-negation-example.html"
- "Immunization-negation-example.html"
- "MedicationAdministration-negation-example.html"
- "MedicationDispense-negation-example.html"
- "MedicationRequest-negation-example.html"
- "Observation-negation-example.html"
- "Procedure-negation-example.html"
- "ServiceRequest-negation-example.html"

Also https://github.com/HL7/fhir-qi-core/blob/master/pages/_includes/qicore-medication-ex.html still has a description suggesting negation, but that example is not a negation example. This was the problem with FHIR-24045, along with the need for negation examples (provided in PR66).

https://jira.hl7.org/browse/FHIR-24045

**Comment by brynrhodes** [comment]
Addressed in https://github.com/HL7/fhir-qi-core/commit/e7e91efbec6b5a02724221b0de02b6696ab0cbe2
