### ISSUE TITLE
system code and display not needed with negation example

### ISSUE THREAD

**Issue by p9g** [HL7/fhir-qi-core#79]
[1] https://github.com/HL7/fhir-qi-core/blob/master/resources/procedure-negation-example.xml#L23

Should the following be removed from [1] since the valueset-reference extension was added?
```
<system value="http://snomed.info/sct"/>
<code value="80146002"/>
<display value="Excision of appendix (procedure)"/>
```

Probably applicable to other negation examples as well.

**Comment by brynrhodes** [comment]
Agreed and corrected, thanks Paul!

**Comment by p9g** [comment]
Fixed in https://github.com/HL7/fhir-qi-core/commit/53b2cf9da4186282312b4a7cc89306d7bf1e1687
